# syntax=docker/dockerfile:1
FROM amazoncorretto:17

ARG SPRING_PROFILES_ACTIVE=prod
ARG DATABASE_ADDRESS=db.gooiman.internal
ARG DATABASE_USERNAME=root
ARG DATABASE_PASSWORD=password
ARG JWT_SECRET=9bc0a269dbe8910fa16ced43ef5d14113a120fe1ab2d9b66bbd4c9bc0a269dbe8910fa16ced43ef5d14113
ARG JWT_TOKEN_VALIDITY_TIME=86400000
ARG KEYSTORE_PASSWORD=changeit
ARG BLACKLIST_VALIDITY_TIME=86400000

ENV spring.datasource.initialization-mode=always
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATABASE_ADDRESS=${DATABASE_ADDRESS}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_TOKEN_VALIDITY_TIME=${JWT_TOKEN_VALIDITY_TIME}
ENV BLACKLIST_VALIDITY_TIME=${BLACKLIST_VALIDITY_TIME}

COPY ./build/libs/gooiman-server-0.0.1-SNAPSHOT.jar /opt/application.jar

WORKDIR /opt/

CMD ["java", "-jar", "/opt/application.jar"]