version: 0.0
os: linux
files:
  - source: /
    destination: /var/deployment
    overwrite: yes
  - source: /compose/docker-compose.yml
    destination: /var/deployment
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root