name: gooiman-server
services:
  api:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "443:443"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis.gooiman.internal