spring:
  application:
    name: gooiman-server
  datasource:
    url: "jdbc:mysql://${DATABASE_ADDRESS}:3306/gooiman?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&maxReconnects=10"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    secret: ${JWT_SECRET}
    token-validity-time: ${JWT_TOKEN_VALIDITY_TIME}
    blacklist-validity-time: ${BLACKLIST_VALIDITY_TIME}

springdoc:
  packages-to-scan: dev.gooiman.server
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha