spring:
  application:
    name: gooiman-server
  datasource:
    url: "jdbc:mysql://${DATABASE_ADDRESS}:3306/gooiman?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&maxReconnects=10"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG